# This file was automatically generated by Vpl
if { ![info exists _is_init_cmds] } {
  set vivado_error_file vivado_error.txt
  set vivado_warn_file vivado_warning.txt

  source ../../../.local/ocl_util.tcl
  source ../../../.local/platform.tcl
  namespace import ocl_util::*

  set _is_init_cmds true
}


# generate cookie file for messaging
write_cookie_file_impl "binary_container_1"

# utilization reports
report_utilization_impl false "cvtcolor_bgr2hsv" "routed" "" "../../../input" "../../../output"

# kernel service update
update_kernel_info ../../../../../link.steps.log /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour/Hardware/binary_container_1.build/link/int


# run timing analysis and frequency scaling
if { ![report_timing_and_scale_freq "" "dr" "../../../output" "/tools/Xilinx/Vitis/2020.1/workspace/cvtcolour/Hardware/binary_container_1.build/link/int" "kernel_clock_freqs {} system_clock_freqs {} worst_negative_slack 0 max_frequency 650 min_frequency 10 error_on_hold_violation true skip_timing_and_scaling false enable_auto_freq_scale false" "binary_container_1"] } {
  return false
}
