-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cvtcolor_bgr2hsv_Block_split1_proc21 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    rows : IN STD_LOGIC_VECTOR (31 downto 0);
    cols : IN STD_LOGIC_VECTOR (31 downto 0);
    img_bgr : IN STD_LOGIC_VECTOR (63 downto 0);
    img_hsv : IN STD_LOGIC_VECTOR (63 downto 0);
    imgInput0_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    imgInput0_rows_out_full_n : IN STD_LOGIC;
    imgInput0_rows_out_write : OUT STD_LOGIC;
    imgInput0_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    imgInput0_cols_out_full_n : IN STD_LOGIC;
    imgInput0_cols_out_write : OUT STD_LOGIC;
    imgOutput0_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    imgOutput0_rows_out_full_n : IN STD_LOGIC;
    imgOutput0_rows_out_write : OUT STD_LOGIC;
    imgOutput0_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    imgOutput0_cols_out_full_n : IN STD_LOGIC;
    imgOutput0_cols_out_write : OUT STD_LOGIC;
    img_bgr_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    img_bgr_out_full_n : IN STD_LOGIC;
    img_bgr_out_write : OUT STD_LOGIC;
    img_hsv_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    img_hsv_out_full_n : IN STD_LOGIC;
    img_hsv_out_write : OUT STD_LOGIC );
end;


architecture behav of cvtcolor_bgr2hsv_Block_split1_proc21 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal imgInput0_rows_out_blk_n : STD_LOGIC;
    signal imgInput0_cols_out_blk_n : STD_LOGIC;
    signal imgOutput0_rows_out_blk_n : STD_LOGIC;
    signal imgOutput0_cols_out_blk_n : STD_LOGIC;
    signal img_bgr_out_blk_n : STD_LOGIC;
    signal img_hsv_out_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    imgInput0_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_cols_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgInput0_cols_out_blk_n <= imgInput0_cols_out_full_n;
        else 
            imgInput0_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgInput0_cols_out_din <= cols;

    imgInput0_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgInput0_cols_out_write <= ap_const_logic_1;
        else 
            imgInput0_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    imgInput0_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgInput0_rows_out_blk_n <= imgInput0_rows_out_full_n;
        else 
            imgInput0_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgInput0_rows_out_din <= rows;

    imgInput0_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgInput0_rows_out_write <= ap_const_logic_1;
        else 
            imgInput0_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    imgOutput0_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgOutput0_cols_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgOutput0_cols_out_blk_n <= imgOutput0_cols_out_full_n;
        else 
            imgOutput0_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgOutput0_cols_out_din <= cols;

    imgOutput0_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgOutput0_cols_out_write <= ap_const_logic_1;
        else 
            imgOutput0_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    imgOutput0_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgOutput0_rows_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgOutput0_rows_out_blk_n <= imgOutput0_rows_out_full_n;
        else 
            imgOutput0_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    imgOutput0_rows_out_din <= rows;

    imgOutput0_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imgOutput0_rows_out_write <= ap_const_logic_1;
        else 
            imgOutput0_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    img_bgr_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_bgr_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_bgr_out_blk_n <= img_bgr_out_full_n;
        else 
            img_bgr_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_bgr_out_din <= img_bgr;

    img_bgr_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_bgr_out_write <= ap_const_logic_1;
        else 
            img_bgr_out_write <= ap_const_logic_0;
        end if; 
    end process;


    img_hsv_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_hsv_out_blk_n <= img_hsv_out_full_n;
        else 
            img_hsv_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_hsv_out_din <= img_hsv;

    img_hsv_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_hsv_out_write <= ap_const_logic_1;
        else 
            img_hsv_out_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, imgInput0_rows_out_full_n, imgInput0_cols_out_full_n, imgOutput0_rows_out_full_n, imgOutput0_cols_out_full_n, img_bgr_out_full_n, img_hsv_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (img_hsv_out_full_n = ap_const_logic_0) or (img_bgr_out_full_n = ap_const_logic_0) or (imgOutput0_cols_out_full_n = ap_const_logic_0) or (imgOutput0_rows_out_full_n = ap_const_logic_0) or (imgInput0_cols_out_full_n = ap_const_logic_0) or (imgInput0_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
