-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cvtcolor_bgr2hsv_MatStream2AxiStream is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    imgOutput0_414_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    imgOutput0_414_empty_n : IN STD_LOGIC;
    imgOutput0_414_read : OUT STD_LOGIC;
    ldata1_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    ldata1_full_n : IN STD_LOGIC;
    ldata1_write : OUT STD_LOGIC;
    rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    rows_empty_n : IN STD_LOGIC;
    rows_read : OUT STD_LOGIC;
    cols_bound_per_npc_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    cols_bound_per_npc_empty_n : IN STD_LOGIC;
    cols_bound_per_npc_read : OUT STD_LOGIC;
    last_blk_width : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_ext_blocking_n : OUT STD_LOGIC;
    ap_str_blocking_n : OUT STD_LOGIC;
    ap_int_blocking_n : OUT STD_LOGIC );
end;


architecture behav of cvtcolor_bgr2hsv_MatStream2AxiStream is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv11_200 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal imgOutput0_414_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln1241_reg_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal ldata1_blk_n : STD_LOGIC;
    signal icmp_ln882_reg_421 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln878_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rows_blk_n : STD_LOGIC;
    signal cols_bound_per_npc_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_117 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_reg_128 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_reg_139 : STD_LOGIC_VECTOR (9 downto 0);
    signal rows_1_reg_385 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal cols_bound_per_npc_1_reg_390 : STD_LOGIC_VECTOR (31 downto 0);
    signal last_blk_width_read_reg_397 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sub_i_fu_169_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_i_reg_402 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1231_fu_180_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln1231_reg_407 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln1241_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op57_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln1241_fu_200_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln882_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln216_fu_260_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln216_reg_425 : STD_LOGIC_VECTOR (9 downto 0);
    signal j_1_fu_272_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_phi_mux_empty_phi_fu_143_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_conv_i9_i_i4_pn_i_phi_fu_154_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln_fu_251_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter0_conv_i9_i_i4_pn_i_reg_151 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1253_fu_234_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_fu_82 : STD_LOGIC_VECTOR (511 downto 0);
    signal select_ln791_fu_353_p3 : STD_LOGIC_VECTOR (511 downto 0);
    signal or_ln1353_fu_294_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_state5 : BOOLEAN;
    signal mul_ln1231_fu_180_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1231_fu_180_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1246_fu_186_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1246_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1238_fu_206_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln1239_fu_214_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bLast_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xf_bits_per_clock_fu_223_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln1253_fu_230_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln1258_fu_239_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1246_fu_266_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln211_fu_280_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln785_fu_284_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal shl_ln785_fu_288_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln1351_fu_301_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_s_fu_305_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln793_fu_323_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln550_fu_327_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln785_1_fu_333_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal trunc_ln455_fu_319_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln803_fu_343_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal p_Result_s_fu_311_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln785_1_fu_337_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal lshr_ln803_fu_347_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_int_blocking_cur_n : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal mul_ln1231_fu_180_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln1231_fu_180_p10 : STD_LOGIC_VECTOR (63 downto 0);

    component cvtcolor_bgr2hsv_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    mul_32ns_32ns_64_1_1_U101 : component cvtcolor_bgr2hsv_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => mul_ln1231_fu_180_p0,
        din1 => mul_ln1231_fu_180_p1,
        dout => mul_ln1231_fu_180_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ldata1_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    empty_reg_139_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1241_reg_412 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                empty_reg_139 <= add_ln216_reg_425;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                empty_reg_139 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_117_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1241_fu_195_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_117 <= add_ln1241_fu_200_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                indvar_flatten_reg_117 <= ap_const_lv64_0;
            end if; 
        end if;
    end process;

    j_reg_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1241_fu_195_p2 = ap_const_lv1_0))) then 
                j_reg_128 <= j_1_fu_272_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                j_reg_128 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    p_0_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln882_reg_421 = ap_const_lv1_1) and (icmp_ln1241_reg_412 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0_fu_82 <= or_ln1353_fu_294_p2;
            elsif (((icmp_ln882_reg_421 = ap_const_lv1_0) and (icmp_ln1241_reg_412 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0_fu_82 <= select_ln791_fu_353_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (cols_bound_per_npc_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_0_fu_82 <= ap_const_lv512_lc_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1241_fu_195_p2 = ap_const_lv1_0))) then
                add_ln216_reg_425 <= add_ln216_fu_260_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (cols_bound_per_npc_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cols_bound_per_npc_1_reg_390 <= cols_bound_per_npc_dout;
                rows_1_reg_385 <= rows_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1241_reg_412 <= icmp_ln1241_fu_195_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1241_fu_195_p2 = ap_const_lv1_0))) then
                icmp_ln882_reg_421 <= icmp_ln882_fu_245_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                last_blk_width_read_reg_397 <= last_blk_width;
                mul_ln1231_reg_407 <= mul_ln1231_fu_180_p2;
                sub_i_reg_402 <= sub_i_fu_169_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ldata1_full_n, rows_empty_n, cols_bound_per_npc_empty_n, ap_CS_fsm_state5, icmp_ln878_fu_371_p2, icmp_ln1241_fu_195_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (cols_bound_per_npc_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1241_fu_195_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1241_fu_195_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ldata1_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln1241_fu_200_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_117) + unsigned(ap_const_lv64_1));
    add_ln1246_fu_266_p2 <= std_logic_vector(unsigned(j_reg_128) + unsigned(ap_const_lv31_1));
    add_ln216_fu_260_p2 <= std_logic_vector(unsigned(ap_phi_mux_conv_i9_i_i4_pn_i_phi_fu_154_p4) + unsigned(ap_phi_mux_empty_phi_fu_143_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(imgOutput0_414_empty_n, ldata1_full_n, ap_enable_reg_pp0_iter1, icmp_ln1241_reg_412, ap_predicate_op57_write_state4)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln1241_reg_412 = ap_const_lv1_0) and (imgOutput0_414_empty_n = ap_const_logic_0)) or ((ldata1_full_n = ap_const_logic_0) and (ap_predicate_op57_write_state4 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(imgOutput0_414_empty_n, ldata1_full_n, ap_enable_reg_pp0_iter1, icmp_ln1241_reg_412, ap_predicate_op57_write_state4)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln1241_reg_412 = ap_const_lv1_0) and (imgOutput0_414_empty_n = ap_const_logic_0)) or ((ldata1_full_n = ap_const_logic_0) and (ap_predicate_op57_write_state4 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(imgOutput0_414_empty_n, ldata1_full_n, ap_enable_reg_pp0_iter1, icmp_ln1241_reg_412, ap_predicate_op57_write_state4)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln1241_reg_412 = ap_const_lv1_0) and (imgOutput0_414_empty_n = ap_const_logic_0)) or ((ldata1_full_n = ap_const_logic_0) and (ap_predicate_op57_write_state4 = ap_const_boolean_1))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, rows_empty_n, cols_bound_per_npc_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (cols_bound_per_npc_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(imgOutput0_414_empty_n, ldata1_full_n, icmp_ln1241_reg_412, ap_predicate_op57_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((icmp_ln1241_reg_412 = ap_const_lv1_0) and (imgOutput0_414_empty_n = ap_const_logic_0)) or ((ldata1_full_n = ap_const_logic_0) and (ap_predicate_op57_write_state4 = ap_const_boolean_1)));
    end process;


    ap_block_state5_assign_proc : process(ldata1_full_n, icmp_ln878_fu_371_p2)
    begin
                ap_block_state5 <= ((icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ldata1_full_n = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln1241_fu_195_p2)
    begin
        if ((icmp_ln1241_fu_195_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ldata1_full_n, ap_CS_fsm_state5, icmp_ln878_fu_371_p2)
    begin
        if ((not(((icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ldata1_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_ext_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_int_blocking_cur_n <= (rows_blk_n and ldata1_blk_n and imgOutput0_414_blk_n and cols_bound_per_npc_blk_n);
    ap_int_blocking_n <= (ap_int_blocking_cur_n and ap_const_logic_1);

    ap_phi_mux_conv_i9_i_i4_pn_i_phi_fu_154_p4_assign_proc : process(icmp_ln1241_fu_195_p2, icmp_ln882_fu_245_p2, or_ln_fu_251_p3, ap_phi_reg_pp0_iter0_conv_i9_i_i4_pn_i_reg_151, zext_ln1253_fu_234_p1)
    begin
        if ((icmp_ln1241_fu_195_p2 = ap_const_lv1_0)) then
            if ((icmp_ln882_fu_245_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_conv_i9_i_i4_pn_i_phi_fu_154_p4 <= zext_ln1253_fu_234_p1;
            elsif ((icmp_ln882_fu_245_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_conv_i9_i_i4_pn_i_phi_fu_154_p4 <= or_ln_fu_251_p3;
            else 
                ap_phi_mux_conv_i9_i_i4_pn_i_phi_fu_154_p4 <= ap_phi_reg_pp0_iter0_conv_i9_i_i4_pn_i_reg_151;
            end if;
        else 
            ap_phi_mux_conv_i9_i_i4_pn_i_phi_fu_154_p4 <= ap_phi_reg_pp0_iter0_conv_i9_i_i4_pn_i_reg_151;
        end if; 
    end process;


    ap_phi_mux_empty_phi_fu_143_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln1241_reg_412, empty_reg_139, add_ln216_reg_425)
    begin
        if (((icmp_ln1241_reg_412 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_empty_phi_fu_143_p4 <= add_ln216_reg_425;
        else 
            ap_phi_mux_empty_phi_fu_143_p4 <= empty_reg_139;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_conv_i9_i_i4_pn_i_reg_151 <= "XXXXXXXXXX";

    ap_predicate_op57_write_state4_assign_proc : process(icmp_ln1241_reg_412, icmp_ln882_reg_421)
    begin
                ap_predicate_op57_write_state4 <= ((icmp_ln882_reg_421 = ap_const_lv1_0) and (icmp_ln1241_reg_412 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ldata1_full_n, ap_CS_fsm_state5, icmp_ln878_fu_371_p2)
    begin
        if ((not(((icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ldata1_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_str_blocking_n <= (ap_const_logic_1 and ap_const_logic_1);
    bLast_fu_218_p2 <= "1" when (zext_ln1239_fu_214_p1 = sub_i_reg_402) else "0";

    cols_bound_per_npc_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, cols_bound_per_npc_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cols_bound_per_npc_blk_n <= cols_bound_per_npc_empty_n;
        else 
            cols_bound_per_npc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    cols_bound_per_npc_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, rows_empty_n, cols_bound_per_npc_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (cols_bound_per_npc_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            cols_bound_per_npc_read <= ap_const_logic_1;
        else 
            cols_bound_per_npc_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1241_fu_195_p2 <= "1" when (indvar_flatten_reg_117 = mul_ln1231_reg_407) else "0";
    icmp_ln1246_fu_190_p2 <= "1" when (signed(zext_ln1246_fu_186_p1) < signed(cols_bound_per_npc_1_reg_390)) else "0";
    icmp_ln878_fu_371_p2 <= "1" when (empty_reg_139 = ap_const_lv10_0) else "0";
    icmp_ln882_fu_245_p2 <= "1" when (unsigned(ap_phi_mux_empty_phi_fu_143_p4) < unsigned(sub_ln1258_fu_239_p2)) else "0";

    imgOutput0_414_blk_n_assign_proc : process(imgOutput0_414_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln1241_reg_412)
    begin
        if (((icmp_ln1241_reg_412 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imgOutput0_414_blk_n <= imgOutput0_414_empty_n;
        else 
            imgOutput0_414_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    imgOutput0_414_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln1241_reg_412, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln1241_reg_412 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imgOutput0_414_read <= ap_const_logic_1;
        else 
            imgOutput0_414_read <= ap_const_logic_0;
        end if; 
    end process;

    j_1_fu_272_p3 <= 
        add_ln1246_fu_266_p2 when (icmp_ln1246_fu_190_p2(0) = '1') else 
        ap_const_lv31_1;

    ldata1_blk_n_assign_proc : process(ldata1_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln1241_reg_412, icmp_ln882_reg_421, ap_CS_fsm_state5, icmp_ln878_fu_371_p2)
    begin
        if ((((icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln882_reg_421 = ap_const_lv1_0) and (icmp_ln1241_reg_412 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ldata1_blk_n <= ldata1_full_n;
        else 
            ldata1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ldata1_din_assign_proc : process(ldata1_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_state5, icmp_ln878_fu_371_p2, ap_predicate_op57_write_state4, p_0_fu_82, or_ln1353_fu_294_p2, ap_block_pp0_stage0_01001)
    begin
        if ((not(((icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ldata1_full_n = ap_const_logic_0))) and (icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ldata1_din <= p_0_fu_82;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op57_write_state4 = ap_const_boolean_1))) then 
            ldata1_din <= or_ln1353_fu_294_p2;
        else 
            ldata1_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ldata1_write_assign_proc : process(ldata1_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_state5, icmp_ln878_fu_371_p2, ap_predicate_op57_write_state4, ap_block_pp0_stage0_11001)
    begin
        if (((not(((icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ldata1_full_n = ap_const_logic_0))) and (icmp_ln878_fu_371_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op57_write_state4 = ap_const_boolean_1)))) then 
            ldata1_write <= ap_const_logic_1;
        else 
            ldata1_write <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln803_fu_347_p2 <= std_logic_vector(shift_right(unsigned(zext_ln211_fu_280_p1),to_integer(unsigned('0' & zext_ln803_fu_343_p1(31-1 downto 0)))));
    mul_ln1231_fu_180_p0 <= mul_ln1231_fu_180_p00(32 - 1 downto 0);
    mul_ln1231_fu_180_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cols_bound_per_npc_1_reg_390),64));
    mul_ln1231_fu_180_p1 <= mul_ln1231_fu_180_p10(32 - 1 downto 0);
    mul_ln1231_fu_180_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rows_1_reg_385),64));
    or_ln1353_fu_294_p2 <= (shl_ln785_fu_288_p2 or p_0_fu_82);
    or_ln_fu_251_p3 <= (ap_const_lv5_10 & sext_ln1253_fu_230_p1);
    p_Result_s_fu_311_p3 <= p_Val2_s_fu_305_p2(10 downto 10);
    p_Val2_s_fu_305_p2 <= std_logic_vector(unsigned(ap_const_lv11_200) - unsigned(zext_ln1351_fu_301_p1));

    rows_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, rows_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rows_blk_n <= rows_empty_n;
        else 
            rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rows_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, rows_empty_n, cols_bound_per_npc_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (cols_bound_per_npc_empty_n = ap_const_logic_0) or (rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            rows_read <= ap_const_logic_1;
        else 
            rows_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln1238_fu_206_p3 <= 
        j_reg_128 when (icmp_ln1246_fu_190_p2(0) = '1') else 
        ap_const_lv31_0;
    select_ln791_fu_353_p3 <= 
        shl_ln785_1_fu_337_p2 when (p_Result_s_fu_311_p3(0) = '1') else 
        lshr_ln803_fu_347_p2;
        sext_ln1253_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xf_bits_per_clock_fu_223_p3),5));

    shl_ln785_1_fu_337_p2 <= std_logic_vector(shift_left(unsigned(zext_ln211_fu_280_p1),to_integer(unsigned('0' & zext_ln785_1_fu_333_p1(31-1 downto 0)))));
    shl_ln785_fu_288_p2 <= std_logic_vector(shift_left(unsigned(zext_ln211_fu_280_p1),to_integer(unsigned('0' & zext_ln785_fu_284_p1(31-1 downto 0)))));
    sub_i_fu_169_p2 <= std_logic_vector(unsigned(cols_bound_per_npc_1_reg_390) + unsigned(ap_const_lv32_FFFFFFFF));
    sub_ln1258_fu_239_p2 <= std_logic_vector(signed(ap_const_lv10_200) - signed(zext_ln1253_fu_234_p1));
    sub_ln550_fu_327_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(trunc_ln793_fu_323_p1));
    trunc_ln455_fu_319_p1 <= p_Val2_s_fu_305_p2(10 - 1 downto 0);
    trunc_ln793_fu_323_p1 <= p_Val2_s_fu_305_p2(9 - 1 downto 0);
    xf_bits_per_clock_fu_223_p3 <= 
        last_blk_width_read_reg_397 when (bLast_fu_218_p2(0) = '1') else 
        ap_const_lv4_8;
    zext_ln1239_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1238_fu_206_p3),32));
    zext_ln1246_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_128),32));
    zext_ln1253_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1253_fu_230_p1),10));
    zext_ln1351_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_139),11));
    zext_ln211_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(imgOutput0_414_dout),512));
    zext_ln785_1_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln550_fu_327_p2),512));
    zext_ln785_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_139),512));
    zext_ln803_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln455_fu_319_p1),512));
end behav;
