# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour/Hardware/binary_container_1.build/link/vivado/vpl/output/zcu104_base_ooc_copy.xdc

# Block Designs: bd/zcu104_base/zcu104_base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base || ORIG_REF_NAME==zcu104_base} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_axi_intc_0_0/zcu104_base_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_axi_intc_0_0 || ORIG_REF_NAME==zcu104_base_axi_intc_0_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_axi_interconnect_hpc0_0/zcu104_base_axi_interconnect_hpc0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_axi_interconnect_hpc0_0 || ORIG_REF_NAME==zcu104_base_axi_interconnect_hpc0_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_axi_register_slice_0_0/zcu104_base_axi_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_axi_register_slice_0_0 || ORIG_REF_NAME==zcu104_base_axi_register_slice_0_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_axi_vip_0_0/zcu104_base_axi_vip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_axi_vip_0_0 || ORIG_REF_NAME==zcu104_base_axi_vip_0_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_axi_vip_1_0/zcu104_base_axi_vip_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_axi_vip_1_0 || ORIG_REF_NAME==zcu104_base_axi_vip_1_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_clk_wiz_0_0/zcu104_base_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_clk_wiz_0_0 || ORIG_REF_NAME==zcu104_base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_interconnect_axifull_0/zcu104_base_interconnect_axifull_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_interconnect_axifull_0 || ORIG_REF_NAME==zcu104_base_interconnect_axifull_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_interconnect_axihpm0fpd_0/zcu104_base_interconnect_axihpm0fpd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_interconnect_axihpm0fpd_0 || ORIG_REF_NAME==zcu104_base_interconnect_axihpm0fpd_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_interconnect_axilite_0/zcu104_base_interconnect_axilite_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_interconnect_axilite_0 || ORIG_REF_NAME==zcu104_base_interconnect_axilite_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_proc_sys_reset_0_0/zcu104_base_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_proc_sys_reset_0_0 || ORIG_REF_NAME==zcu104_base_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_proc_sys_reset_1_0/zcu104_base_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_proc_sys_reset_1_0 || ORIG_REF_NAME==zcu104_base_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_proc_sys_reset_2_0/zcu104_base_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_proc_sys_reset_2_0 || ORIG_REF_NAME==zcu104_base_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_proc_sys_reset_3_0/zcu104_base_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_proc_sys_reset_3_0 || ORIG_REF_NAME==zcu104_base_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_proc_sys_reset_4_0/zcu104_base_proc_sys_reset_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_proc_sys_reset_4_0 || ORIG_REF_NAME==zcu104_base_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_proc_sys_reset_5_0/zcu104_base_proc_sys_reset_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_proc_sys_reset_5_0 || ORIG_REF_NAME==zcu104_base_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_proc_sys_reset_6_0/zcu104_base_proc_sys_reset_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_proc_sys_reset_6_0 || ORIG_REF_NAME==zcu104_base_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_ps_e_0/zcu104_base_ps_e_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_ps_e_0 || ORIG_REF_NAME==zcu104_base_ps_e_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_xbar_0/zcu104_base_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_xbar_0 || ORIG_REF_NAME==zcu104_base_xbar_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_cvtcolor_bgr2hsv_1_0/zcu104_base_cvtcolor_bgr2hsv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_cvtcolor_bgr2hsv_1_0 || ORIG_REF_NAME==zcu104_base_cvtcolor_bgr2hsv_1_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_xbar_1/zcu104_base_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_xbar_1 || ORIG_REF_NAME==zcu104_base_xbar_1} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_axi_ic_ps_e_S_AXI_HP0_FPD_0/zcu104_base_axi_ic_ps_e_S_AXI_HP0_FPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_axi_ic_ps_e_S_AXI_HP0_FPD_0 || ORIG_REF_NAME==zcu104_base_axi_ic_ps_e_S_AXI_HP0_FPD_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_axi_intc_0_intr_1_interrupt_concat_0/zcu104_base_axi_intc_0_intr_1_interrupt_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_axi_intc_0_intr_1_interrupt_concat_0 || ORIG_REF_NAME==zcu104_base_axi_intc_0_intr_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_irq_const_tieoff_0/zcu104_base_irq_const_tieoff_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_irq_const_tieoff_0 || ORIG_REF_NAME==zcu104_base_irq_const_tieoff_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_auto_us_0/zcu104_base_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_auto_us_0 || ORIG_REF_NAME==zcu104_base_auto_us_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_auto_pc_0/zcu104_base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_auto_pc_0 || ORIG_REF_NAME==zcu104_base_auto_pc_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_m01_regslice_0/zcu104_base_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_m01_regslice_0 || ORIG_REF_NAME==zcu104_base_m01_regslice_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_auto_cc_0/zcu104_base_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_auto_cc_0 || ORIG_REF_NAME==zcu104_base_auto_cc_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_s00_regslice_0/zcu104_base_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_s00_regslice_0 || ORIG_REF_NAME==zcu104_base_s00_regslice_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_s00_data_fifo_0/zcu104_base_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_s00_data_fifo_0 || ORIG_REF_NAME==zcu104_base_s00_data_fifo_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_s01_regslice_0/zcu104_base_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_s01_regslice_0 || ORIG_REF_NAME==zcu104_base_s01_regslice_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_s01_data_fifo_0/zcu104_base_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_s01_data_fifo_0 || ORIG_REF_NAME==zcu104_base_s01_data_fifo_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_m00_data_fifo_0/zcu104_base_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_m00_data_fifo_0 || ORIG_REF_NAME==zcu104_base_m00_data_fifo_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_m00_regslice_0/zcu104_base_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_m00_regslice_0 || ORIG_REF_NAME==zcu104_base_m00_regslice_0} -quiet] -quiet

# IP: bd/zcu104_base/ip/zcu104_base_auto_ds_0/zcu104_base_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zcu104_base_auto_ds_0 || ORIG_REF_NAME==zcu104_base_auto_ds_0} -quiet] -quiet

# XDC: bd/zcu104_base/zcu104_base_ooc.xdc
