catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

set vpp_optimize_level 0
open_project cvtcolor_bgr2hsv
set_top cvtcolor_bgr2hsv
add_files "/tools/Xilinx/Vitis/2020.1/workspace/cvtcolour/src/xf_cvt_color_accel.cpp" -cflags " -g -I /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour/src -I /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour/libs/xf_opencv/L1/include -I /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour/src/build "
open_solution -flow_target vitis solution
set_part xczu7ev-ffvc1156-2-e
create_clock -period 150.000000MHz -name default
config_rtl -kernel_profile
config_export -vivado_optimization_level $vpp_optimize_level
config_dataflow -strict_mode warning
config_debug -enable
set_clock_uncertainty 27.000000%
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
config_interface -default_slave_interface s_axilite
config_export -format ip_catalog -ipname cvtcolor_bgr2hsv
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
