runners:
 AWS-runner:
  image: ubuntu-vitis-2020-1

jobs:   
 build-SW-emu:
  runner: AWS-runner
  type:
   build: software
  input: 
   artifact: 
    - platform/zcu104-firmware
    - bbx/petalinux-sysroot
    - bbx/petalinux-firmware
    - bbx/vitis-libraries
  steps:
   - run:
      name: Run Software Emulation Build
      command: Emulation-SW/build.sh
      type: sw-emulation    
   - run:
      name: Download files
      command: |
       git clone https://github.com/mwijeyasinghebbx/test_images
       mv test_images/* /tmp/xilinx_zcu104_base_202010_1/sw/xilinx_zcu104_base_202010_1/xrt/image/
      type: miscellaneous  
 test-sw-emulation:
  runner: AWS-runner
  depends:
   - build-SW-emu
  type:
   test: sw-emulation
  input: 
   artifact: 
    - build-SW-emu
    - bbx/zcu104-firmware
  steps:
   - run:
      name: Run Software Emulation
      command: ./sw_emu.sh 
   - run:
      name: Software Emulation
      command: echo "Running Software Emulation" 
 build-HW-emu:
  runner: AWS-runner
  type:
   build: hw-emulation
  input: 
   artifact: 
    - platform/zcu104-firmware
    - bbx/petalinux-sysroot
    - bbx/petalinux-firmware
    - bbx/vitis-libraries
  steps:
   - run:
      name: Run Hardware Emulation Build
      command: Emulation-HW/build.sh
      type: hw-emulation  
 test-hw-emulation:
  runner: AWS-runner
  depends:
   - build-HW-emu
  type:
   test: hw-emulation
  input: 
   artifact: 
    - build-HW-emu
    - bbx/zcu104-firmware
  steps:
   - run:
      name: Hardware Emulation
      command: ./hw_emu.sh 
 build-HW:
  runner: AWS-runner
  type:
   build: hardware
  input: 
   artifact: 
    - platform/zcu104-firmware
    - bbx/petalinux-sysroot
    - bbx/petalinux-firmware
    - bbx/vitis-libraries
  steps:
   - run:
      name: Build HW
      command: Hardware/build.sh
      type: Hardware 
workflows:
 complete-build-test:
  jobs:
   - build-SW-emu
   - test-sw-emulation
   - build-HW-emu
   - build-HW
