runners:
 AWS-runner:
  image: ubuntu-vitis-2020-1


jobs:   
 build-SW-emu:
  runner: AWS-runner
  type:
   build: software
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour       
  input: 
   artifact: 
    - xilinx_zcu104_base_202010_1.zip
    - aarch64-xilinx-linux2020_1.zip
    - xilinx-zynqmp-common-v2020.1.tar.gz
    - Vitis_Libraries_2020_1.tar.gz
  output:
   artifact:
    - Emulation-SW
    - sw_emu.sh
  steps:
   - run:
      name: Download files
      command: |
       git clone https://github.com/mwijeyasinghebbx/test_images
       mv test_images/* /tools/Xilinx/Vitis/2020.1/platforms/xilinx_zcu104_base_202010_1/sw/xilinx_zcu104_base_202010_1/xrt/image/
   - run:
      name: Run Software Emulation Build
      command: time Emulation-SW/build.sh
 test-sw-emulation:
  runner: AWS-runner
  depends:
   - build-SW-emu
  type:
   test: sw-emulation
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour       
  input: 
   artifact: 
    - build-SW-emu
    - xilinx_zcu104_base_202010_1.zip
  steps:
   - run:
      name: Run Software Emulation
      command: time ./sw_emu.sh 
 build-HW-emu:
  runner: AWS-runner
  type:
   build: hw-emulation
  output:
   artifact:
    - Emulation-HW
    - hw_emu.sh
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour           
  input: 
   artifact: 
    - xilinx_zcu104_base_202010_1.zip
    - aarch64-xilinx-linux2020_1.zip
    - xilinx-zynqmp-common-v2020.1.tar.gz
    - Vitis_Libraries_2020_1.tar.gz
  steps:
   - run:
      name: Download files
      command: |
       git clone https://github.com/mwijeyasinghebbx/test_images
       mv test_images/* /tools/Xilinx/Vitis/2020.1/platforms/xilinx_zcu104_base_202010_1/sw/xilinx_zcu104_base_202010_1/xrt/image/
   - run:
      name: Run Hardware Emulation Build
      command: time Emulation-HW/build.sh
 test-hw-emulation:
  runner: AWS-runner
  depends:
   - build-HW-emu
  type:
   test: hw-emulation
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour          
  input: 
   artifact: 
    - build-HW-emu
    - xilinx_zcu104_base_202010_1.zip
  steps:
   - run:
      name: Hardware Emulation
      command: time ./hw_emu.sh 
 build-HW:
  runner: AWS-runner
  type:
   build: hardware
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/cvtcolour          
  input: 
   artifact: 
    - xilinx_zcu104_base_202010_1.zip
    - aarch64-xilinx-linux2020_1.zip
    - xilinx-zynqmp-common-v2020.1.tar.gz
    - Vitis_Libraries_2020_1.tar.gz
  steps:
   - run:
      name: Build HW
      command: time Hardware/build.sh
      type: Hardware 
workflows:
 complete-build-test:
  jobs:
   - build-SW-emu
   - build-HW-emu
   - build-HW
   - test-sw-emulation
   - test-hw-emulation   


