runners:
 AWS-runner:
  image: ubuntu-vitis-2020-1
jobs:   
 build-HW:
  runner: AWS-runner
  type:
   build: hardware
  input: 
   artifact: 
    - platform/zcu104-firmware
    - bbx/petalinux-sysroot
    - bbx/petalinux-firmware
    - bbx/vitis-libraries
  steps:
   - run:
      name: Build HW
      command: Hardware/build.sh
      type: Hardware 
workflows:
 complete-build-test:
  jobs:
   - build-HW
